"""sync_models_with_db

Revision ID: 5c7b93541fb9
Revises: 001
Create Date: 2025-12-14 15:22:14.145280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c7b93541fb9'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('batches_product_id_fkey'), 'batches', type_='foreignkey')
    op.drop_column('batches', 'product_id')
    op.create_index(op.f('ix_marking_codes_code_raw'), 'marking_codes', ['code_raw'], unique=False)
    op.create_index(op.f('ix_marking_codes_sntin'), 'marking_codes', ['sntin'], unique=False)
    op.add_column('orders', sa.Column('name', sa.String(), server_default='unknown', nullable=True))
    op.add_column('orders', sa.Column('gtin', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('batch_id', sa.Integer(), nullable=False))
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('ORDERING', 'READY', 'ERROR', name='orderstatus'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'orders', 'batches', ['batch_id'], ['id'])
    op.drop_column('orders', 'prod_date')
    op.drop_column('orders', 'batch_number')
    op.drop_column('orders', 'exp_date')
    op.add_column('products', sa.Column('color', sa.String(), nullable=True))
    op.add_column('products', sa.Column('venchik', sa.String(), nullable=True))
    op.add_column('products', sa.Column('size', sa.String(), nullable=True))
    op.add_column('products', sa.Column('units_per_pack', sa.Integer(), nullable=True))
    # Создаем constraint только если не существует
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'uq_sscc_counters_date'
            ) THEN
                ALTER TABLE sscc_counters ADD CONSTRAINT uq_sscc_counters_date UNIQUE (date);
            END IF;
        END$$;
    """)
    op.alter_column('task_log', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_log', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint('uq_sscc_counters_date', 'sscc_counters', type_='unique')
    op.drop_column('products', 'units_per_pack')
    op.drop_column('products', 'size')
    op.drop_column('products', 'venchik')
    op.drop_column('products', 'color')
    op.add_column('orders', sa.Column('exp_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('batch_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('prod_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ORDERING', 'READY', 'ERROR', name='orderstatus'),
               existing_nullable=False)
    op.drop_column('orders', 'batch_id')
    op.drop_column('orders', 'gtin')
    op.drop_column('orders', 'name')
    op.drop_index(op.f('ix_marking_codes_sntin'), table_name='marking_codes')
    op.drop_index(op.f('ix_marking_codes_code_raw'), table_name='marking_codes')
    op.add_column('batches', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('batches_product_id_fkey'), 'batches', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
